# Generated by Django 5.0.4 on 2024-05-23 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('budget', models.IntegerField()),
                ('project_deadline', models.DateField()),
                ('application_deadline', models.DateField()),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_archived', models.BooleanField(blank=True, default=False)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='laboratory_projects', to='laboratory.laboratory', verbose_name='Лаборатория')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
