# Generated by Django 5.0.4 on 2024-05-26 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
        ('jobopen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='requirements',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='application',
            name='project',
        ),
        migrations.RemoveField(
            model_name='application',
            name='salary',
        ),
        migrations.AddField(
            model_name='application',
            name='job_open',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applied_jobs', to='jobopen.jobopen', verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
